spring:
  jpa:
    database: postgresql
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      INDENT_OUTPUT: true
